name: Node CI

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        node-version: ['10', '12', '14', '16']

    name: Use node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make install
      - run: make test

  build:
    needs: [test]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: make install
      - name: Run linter
        run: make lint
      - name: Run test-coverage
        run: make test-coverage
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TEST_REPORTER_ID }}
